### ISSUE TITLE
No Authenticate Response Returned

### ISSUE THREAD

**Issue by Steve-MyLiveGuard** [nestlabs/android-sdk#32] opened 2017-05-12 08:48 UTC
Hi, am encountering an issue this morning that hasn't appeared previously.

When entering the method `authenticate(NestToken token)` with a token, none of the three set responses are being returned anymore. Is this an issue with the code or could it be my apps' credentials are no longer valid?

Here is the code from the sample app (have highlighted the log I've placed to see how far it gets):

`private void authenticate(NestToken token) {

        **_Log.v(TAG, "authenticate method entered with token: " + token);_**

        mNest.authWithToken(token, new NestListener.AuthListener() {

            @Override
            public void onAuthSuccess() {
                Log.v(TAG, "Authentication succeeded.");
                fetchData();
            }

            @Override
            public void onAuthFailure(NestException exception) {
                Log.e(TAG, "Authentication failed with error: " + exception.getMessage());
                Settings.saveAuthToken(mActivity, null);
                mNest.launchAuthFlow(mActivity, AUTH_TOKEN_REQUEST_CODE);
            }

            @Override
            public void onAuthRevoked() {
                Log.e(TAG, "Auth token was revoked!");
                Settings.saveAuthToken(mActivity, null);
                mNest.launchAuthFlow(mActivity, AUTH_TOKEN_REQUEST_CODE);
            }
        });
    }`

Please let me know if you need any further info.

**Comment by harenj** [comment] 2017-05-12 16:04
It looks like version 5.6.2 broke the Nest SDK. This is a firmware upgrade for the Nest thermostat that just came out on 5/1/17. I just personally received it on 5/9/17. It seems that a wider roll out is happening in the last 24 hours because I am getting emails from my users saying my app doesn't work anymore.

Here is the changelog: https://nest.com/ca/support/article/Nest-Learning-Thermostat-software-update-history

**Comment by harenj** [comment] 2017-05-12 18:21
@daveecker-nest @aurman @ryanseys - I wanted to give you guys a heads up ASAP. Can you confirm that firmware 5.6.2 broke the Android SDK?

**Comment by davin12x** [comment] 2017-05-12 19:34
Not working for me either

**Comment by harenj** [comment] 2017-05-13 05:19
I think things might be working again. @davin12x @Steve-MyLiveGuard can you re-check?

**Comment by Steve-MyLiveGuard** [comment] 2017-05-13 09:33
Hi @harenj,  looks like it is back up and running across our apps.

**Comment by davin12x** [comment] 2017-05-14 00:01
Yes, it works for me now

**Comment by aurman** [comment] 2017-05-14 18:35
Apologies for the delay in responding. We tracked this down to a service issue and rolled back to determine the issue. The issue isn't related to the SDK itself and should be working again. I'll close the issue but if it happens again please submit a new one or visit https://nestdevelopers.io

**Closed by aurman** 2017-05-14 18:35 UTC
